### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by FarhanAliRaza**
In newer version of sveltekit config.kit.vite has been removed. Now vite related configs are in vite.config.js

### CODE REVIEW

**Comment by FarhanAliRaza** [comment]
@IgnusG  @JustinVoitel  Should i close this pull request?

**Review by JustinVoitel — COMMENTED** [review]
I think its a good idea to remove the old syntax and only have the new one since it's still in beta

**Comment by FarhanAliRaza** [comment]
Sorry, this is my first pull request. What can i do?

**Comment by JustinVoitel** [comment]
I'am a noob too in PR's :D 
I think you can add another commit to the branch with the proposed changes

**Comment by IgnusG** [comment]
Hey guys, GitHub sent me a notification because I was apparently mentioned (I cannot find where). How are you doing?

**Comment by JustinVoitel** [comment]
@IgnusG I cannot find it either 😅 
Can you help us noobs finish this PR ? Like what do we have to do to add onto his commit

**Comment by IgnusG** [comment]
> @IgnusG I cannot find it either 😅 Can you help us noobs finish this PR ? Like what do we have to do to add onto his commit

@FarhanAliRaza have you removed the branch you are trying to merge here in the PR? And are you trying to add more code to it or something else?

**Comment by FarhanAliRaza** [comment]
I deleted the head repository for this commit so i think  i can not change it So we can close this one and i created a new pull request

**Comment by IgnusG** [comment]
You can also create a branch with the same name - GitHub should pick it up 🙂

**Pull request closed without merging**
